/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://flowsub.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Footer}
 */
export type FooterProps = {};

/**
 * Footer
 *
 * @see {@link https://flowsub.design.webflow.com | Source site in Webflow}
 */
export function Footer({}: FooterProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"footer_section-wrapper"}
        grid={{
          type: "section",
        }}
        tag={"footer"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Block className={"footer_content-wrapper"} tag={"div"}>
            <Link
              block={"inline"}
              button={false}
              className={"logo-container"}
              options={{
                href: "/privacy-policy",
              }}
            >
              <Image
                alt={""}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/64a42455c0e137bdb5e7838e/64e1f5d44d124e8656196541_Logo.svg"
                }
                width={"auto"}
              />
            </Link>
            <Block className={"footer-link-wrapper"} tag={"div"}>
              <Link
                block={""}
                button={false}
                className={"nav-link"}
                options={{
                  href: "/terms-of-service",
                }}
              >
                {"Terms of Service"}
              </Link>
              <Link
                block={""}
                button={false}
                className={"nav-link"}
                options={{
                  href: "/privacy-policy",
                }}
              >
                {"Privacy Policy"}
              </Link>
            </Block>
          </Block>
        </Block>
      </Section>
    </div>
  );
}
